import { defineStore } from "pinia";

export const useDiningStore = defineStore("dining", {
  // state定义状态
  state: () => ({
  grids :[{
    diningContact: "dummy",
    diningId: -1,
    diningInfo: "dummy",
    diningName: "dummy",
    diningPrice: "dummy",
    diningTags: ["dummy","dummy"],
    diningTime: "dummy",
    diningUser: "dummy",
    diningUserId: "dummy",
  },
  {
    diningContact: "dummy",
    diningId: -1,
    diningInfo: "dummy",
    diningName: "dummy",
    diningPrice: "dummy",
    diningTags: ["dummy","dummy"],
    diningTime: "dummy",
    diningUser: "dummy",
    diningUserId: "dummy",
  },
  {
    diningContact: "dummy",
    diningId: -1,
    diningInfo: "dummy",
    diningName: "dummy",
    diningPrice: "dummy",
    diningTags: ["dummy","dummy"],
    diningTime: "dummy",
    diningUser: "dummy",
    diningUserId: "dummy",
  },
  {
    diningContact: "dummy",
    diningId: -1,
    diningInfo: "dummy",
    diningName: "dummy",
    diningPrice: "dummy",
    diningTags: ["dummy","dummy"],
    diningTime: "dummy",
    diningUser: "dummy",
    diningUserId: "dummy",
  },
  {
    diningContact: "dummy",
    diningId: -1,
    diningInfo: "dummy",
    diningName: "dummy",
    diningPrice: "dummy",
    diningTags: ["dummy","dummy"],
    diningTime: "dummy",
    diningUser: "dummy",
    diningUserId: "dummy",
  },
  {
    diningContact: "dummy",
    diningId: -1,
    diningInfo: "dummy",
    diningName: "dummy",
    diningPrice: "dummy",
    diningTags: ["dummy","dummy"],
    diningTime: "dummy",
    diningUser: "dummy",
    diningUserId: "dummy",
  },
  {
    diningContact: "dummy",
    diningId: -1,
    diningInfo: "dummy",
    diningName: "dummy",
    diningPrice: "dummy",
    diningTags: ["dummy","dummy"],
    diningTime: "dummy",
    diningUser: "dummy",
    diningUserId: "dummy",
  },
  {
    diningContact: "dummy",
    diningId: -1,
    diningInfo: "dummy",
    diningName: "dummy",
    diningPrice: "dummy",
    diningTags: ["dummy","dummy"],
    diningTime: "dummy",
    diningUser: "dummy",
    diningUserId: "dummy",
  },],
  }),
  actions: {
    increment() {
      this.diningId++;
    },
  },
});

