import { defineStore } from "pinia";

export const useExpressStore = defineStore("express", {
  // state定义状态
  state: () => ({
  grids :[{
    expressCode: "dummy",
    expressContact: "dummy",
    expressId: -1,
    expressInfo: "dummy",
    expressName: "dummy",
    expressPrice: "dummy",
    expressTime: "dummy",
    expressUser: "dummy",
    expressUserId: "dummy",
  },
  {
    expressCode: "dummy",
    expressContact: "dummy",
    expressId: -1,
    expressInfo: "dummy",
    expressName: "dummy",
    expressPrice: "dummy",
    expressTime: "dummy",
    expressUser: "dummy",
    expressUserId: "dummy",
  },
  {
    expressCode: "dummy",
    expressContact: "dummy",
    expressId: -1,
    expressInfo: "dummy",
    expressName: "dummy",
    expressPrice: "dummy",
    expressTime: "dummy",
    expressUser: "dummy",
    expressUserId: "dummy",
  },
  {
    expressCode: "dummy",
    expressContact: "dummy",
    expressId: -1,
    expressInfo: "dummy",
    expressName: "dummy",
    expressPrice: "dummy",
    expressTime: "dummy",
    expressUser: "dummy",
    expressUserId: "dummy",
  },
  {
    expressCode: "dummy",
    expressContact: "dummy",
    expressId: -1,
    expressInfo: "dummy",
    expressName: "dummy",
    expressPrice: "dummy",
    expressTime: "dummy",
    expressUser: "dummy",
    expressUserId: "dummy",
  },
  {
    expressCode: "dummy",
    expressContact: "dummy",
    expressId: -1,
    expressInfo: "dummy",
    expressName: "dummy",
    expressPrice: "dummy",
    expressTime: "dummy",
    expressUser: "dummy",
    expressUserId: "dummy",
  },
  {
    expressCode: "dummy",
    expressContact: "dummy",
    expressId: -1,
    expressInfo: "dummy",
    expressName: "dummy",
    expressPrice: "dummy",
    expressTime: "dummy",
    expressUser: "dummy",
    expressUserId: "dummy",
  },
  {
    expressCode: "dummy",
    expressContact: "dummy",
    expressId: -1,
    expressInfo: "dummy",
    expressName: "dummy",
    expressPrice: "dummy",
    expressTime: "dummy",
    expressUser: "dummy",
    expressUserId: "dummy",
  },],
  }),
  actions: {
    increment() {
      this.expressId++;
    },
  },
});

